export const LOGIN = 'LOGIN';
export const REGISTRATION = 'REGISTRATION';
export const PROFILE_CHANGE = 'PROFILE_CHANGE';
export const CHANGE_STATEMENT = 'CHANGE_STATEMENT';
export const ADD_STATEMENT = 'ADD_STATEMENT';
export const APPROVE_STATEMENT = 'APPROVE_STATEMENT';
export const REMOVE_STATEMENT = 'REMOVE_STATEMENT';
